### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by Alamnzr123** [ThomasAitken/demo-fastapi-async-sqlalchemy#3]
Hi, i want to run application without docker but when it start i get error

```
from app.api.routers.users import router as users_router
ModuleNotFoundError: No module named 'app'
```

any idea how to solve this ?

**Comment by ThomasAitken** [comment]
This is almost certainly related to PYTHONPATH. Inside the `docker-compose.yml` I export `PYTHONPATH=.` from just outside the `app` directory before executing `python app/main.py`. That's one solution.

**Comment by gospodima** [comment]
@Alamnzr123 
Yes, this is for sure `PYTHONPATH`. You can also take a look on my similar [setup](https://github.com/gospodima/async-fastapi-sqlalchemy-template) without docker (@ThomasAitken if you don't mind for such a reference).
